### ISSUE TITLE
Error: Cannot find module '/isbd-server/server.js'

### ISSUE THREAD

**Issue by yulianto** [lromeraj/isbd-server#12]
It seems you forgot to including "build/src/index.js"

root@sbd-directip-01:/isbd-server# ls -ahl
total 316K
drwxr-xr-x   7 root root 4.0K Sep  2 10:52 .
drwxr-xr-x  20 root root 4.0K Sep  2 10:36 ..
-rw-r--r--   1 root root  356 Sep  2 10:36 docker-compose.yml
-rw-r--r--   1 root root  190 Sep  2 10:36 Dockerfile
drwxr-xr-x   9 root root 4.0K Sep  2 10:36 .git
-rw-r--r--   1 root root   32 Sep  2 10:36 .gitignore
-rw-r--r--   1 root root  958 Sep  2 10:36 .gitlab-ci.yml
-rw-r--r--   1 root root  238 Sep  2 10:36 .gitmodules
-rw-r--r--   1 root root  35K Sep  2 10:36 LICENSE
drwxr-xr-x   4 root root 4.0K Sep  2 10:36 modules
drwxr-xr-x 400 root root  16K Sep  2 10:52 node_modules
-rw-r--r--   1 root root  114 Sep  2 10:36 nodemon.json
-rw-r--r--   1 root root  900 Sep  2 10:36 package.json
-rw-r--r--   1 root root 192K Sep  2 10:52 package-lock.json
-rw-r--r--   1 root root 5.7K Sep  2 10:36 README.md
drwxr-xr-x   2 root root 4.0K Sep  2 10:36 scripts
**lrwxrwxrwx   1 root root   18 Sep  2 10:36 server.js -> build/src/index.js**
drwxr-xr-x   3 root root 4.0K Sep  2 10:36 src
-rw-r--r--   1 root root  11K Sep  2 10:36 tsconfig.json
root@sbd-directip-01:/isbd-server#

root@sbd-directip-01:/isbd-server# node server.js --help
internal/modules/cjs/loader.js:934
  throw err;
  ^

Error: Cannot find module '/isbd-server/server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:931:15)
    at Function.Module._load (internal/modules/cjs/loader.js:774:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

**Comment by lukegorman** [comment]
npm run build

**Comment by lromeraj** [comment]
Running `npm install` should be sufficient. Also, ensure Git submodules are initialized for proper dependency setup. If the issue persists, feel free to reopen.
